### ISSUE TITLE
Replacing iconv by iconv-lite

### ISSUE THREAD

**Issue by florian-senn** [Lynbarry/mvg-api#1]
Hey Lynbarry,

I've forked your mvg-api and changed iconv to iconv-lite, due to easier installation and less issues with dependencies, like windows-build-tools, python and so on.

To use it in my own project, I published my version on npm.

As this is my first change to a 'foreign' package, I'm not sure if this fits best practice and I'm asking you how to proceed regarding giving credits to your work.

Thanks for your great work!

**Comment by Lynbarry** [comment]
Hey Florian!

Glad to hear that someone is using this!

I haven't had someone work on a project I started yet, either, so I don't really know what the best practices are.

If you want you can create a pull request from your fork into this project, so that I can also profit from your changes ;)

I think I can also make you a collaborator on this project. The benefit would be that there is only one code base and if one of us adds some functionality or something like that we can both use it.

**Comment by Lynbarry** [comment]
Thanks for creating the pull request!

I went ahead and merged it and released a new version to npm that includes the changes (and some improvements to the README.

**Comment by florian-senn** [comment]
Nice 👍 I marked my package as deprecated and depublish it soon.

Next improvements or changes I'm aiming at are directed towards compatibility with React.js and webpack.

Right now, I'm able to include the API in my React App, but as soon as I want to create a minified build, I get an error thrown. I'll open a new issue for this one.
