### ISSUE TITLE
MVG changed product to UBAHN, SBAHN, BUS, TRAM

### ISSUE THREAD

**Issue by tai42** [Lynbarry/mvg-api#10]
It seems that the MVG changed the product from one letter to words. So a requests should now look like the following: 

mvgApi.getDepartures('Harras', ['UBAHN', 'SBAHN', 'BUS', 'TRAM'])

**Comment by Lynbarry** [comment]
Hey! Thank's for letting me know!

I just released a new version (3.0.0). It works as before again, so you have to use ['u','s','b','t'] again. I thought it would be better to hide the changes in the MVG endpoint and instead provide a consistent interface.

I also added some tests that regularly check if the assumptions my little library makes against the MVG endpoint are still valid. I hope this will notify me quickly if anything changes, so that I can adjust the library quickly, too.
